
vpc_name: demo-vpc
vpc_cidr_block: 10.210.0.0/16
aws_region: ap-northeast-1
vpc_key: demoKey
image: ami-00ab7932c8e82a7b5

vpc_subnets:
  private-a:
    cidr: 10.210.1.0/24
    az: "{{ aws_region }}a"
  public-a:
    cidr: 10.210.2.0/24
    az: "{{ aws_region }}a"

vpc_security_groups:
  - name: allow-public-ssh
    description: "Allow public SSH"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 22
  - name: allow-public-http
    description: "Allow public web traffic"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 80
          - 8080
          - 443