- name: create VPC
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr_block }}"
    region: "{{ aws_region }}"
  register: create_vpc

- name: "set fact: VPC ID"
  set_fact:
    vpc_id: "{{ create_vpc.vpc.id }}"

- name: create VPC subnets
  ec2_vpc_subnet:
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ item.value.cidr }}"
    az: "{{ item.value.az }}"
    region: "{{aws_region}}"
    tags:
      Name: "{{ item.key }}"
  with_dict: "{{ vpc_subnets }}"
  register: create_vpc_subnets

- name: "set fact: VPC subnet IDs"
  set_fact:
    vpc_subnet_ids: "{{ vpc_subnet_ids | default({}) | combine({ item.subnet.tags.Name: item.subnet.id }) }}"
  loop: "{{ create_vpc_subnets.results }}"

- name: create VPC security groups
  ec2_group:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    vpc_id: "{{ vpc_id }}"
    rules: "{{ item.rules }}"
    region: "{{aws_region}}"
  loop: "{{ vpc_security_groups }}"
  register: create_security_groups

- name: "set fact: Security Groups"
  set_fact:
    security_groups: "{{ security_groups | default({}) | combine({ item.group.name: item.name }) }}"
  loop: "{{ create_security_groups.results }}"

- name: create EC2 key
  ec2_key:
    name: "{{ vpc_key }}"
    region: "{{aws_region}}"
  register : ec2_key

- name: print EC2 key
  debug:
    msg: " the key is : {{ec2_key.key.private_key}}"
  ignore_errors: true

# create a private hosted zone for the VPC with the Ansible module
#- name: create Route 53 private hosted zone
#  route53_zone:
#    zone: "{{ vpc_dns_zone }}"
#    state: present
#    vpc_id: "{{ vpc_id }}"
#    vpc_region: "{{ aws_region }}"